USE [master]
GO

/****** Object:  Database [AguilaCurda]    Script Date: 17/11/2019 16:37:05 ******/
CREATE DATABASE [AguilaCurda]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AguilaCurda', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\AguilaCurda.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AguilaCurda_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\AguilaCurda_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AguilaCurda].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AguilaCurda] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AguilaCurda] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AguilaCurda] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AguilaCurda] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AguilaCurda] SET ARITHABORT OFF 
GO

ALTER DATABASE [AguilaCurda] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [AguilaCurda] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AguilaCurda] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AguilaCurda] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AguilaCurda] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AguilaCurda] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AguilaCurda] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AguilaCurda] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AguilaCurda] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AguilaCurda] SET  ENABLE_BROKER 
GO

ALTER DATABASE [AguilaCurda] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AguilaCurda] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AguilaCurda] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AguilaCurda] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AguilaCurda] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AguilaCurda] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AguilaCurda] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AguilaCurda] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AguilaCurda] SET  MULTI_USER 
GO

ALTER DATABASE [AguilaCurda] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AguilaCurda] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AguilaCurda] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AguilaCurda] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AguilaCurda] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AguilaCurda] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AguilaCurda] SET  READ_WRITE 
GO

